# -*- coding: utf-8 -*-
"""ml-obesity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mOwe2pSHyObtFkNSeUToid7iHzEc0yD

# Obesity Dataset — End-to-End Machine Learning Project

## Overview

This project applies machine learning techniques to an obesity dataset to understand relationships between demographic, lifestyle, physical activity, and health-related factors.

The project covers three major machine learning tasks:

1. **Regression** — Predict Weight
2. **Classification** — Predict Obesity Level
3. **Unsupervised Learning** — Discover behavioral/lifestyle clusters using K-Means

### Machine Learning Models Used

#### Regression
- Linear Regression
- Ridge Regression
- Lasso Regression

#### Classification
- Logistic Regression
- K-Nearest Neighbors (KNN)
- Decision Tree
- Random Forest

#### Clustering
- K-Means Clustering

### Key Techniques

- Exploratory Data Analysis (EDA)
- Data Cleaning
- Feature Engineering
- Categorical Encoding
- Feature Scaling
- Train/Test Split
- Model Evaluation
- Hyperparameter-free model comparison
- K-Means clustering
- Elbow Method
- Silhouette Score
- PCA Visualization
- Cluster Profiling

## 1. Import Libraries

Import the Python libraries required for data manipulation, visualization, and exploratory analysis.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## 2. Load the Dataset

Load the obesity dataset into a Pandas DataFrame and inspect the first few records.
"""

df=pd.read_csv('/content/ObesityDataSet_raw_and_data_sinthetic.csv')
df.head()

"""## 3. Dataset Overview

Understand the structure of the dataset by examining:

- Data types
- Numerical statistics
- Column names
- Number of rows and columns
- Categorical distributions
"""

df.info()

df.describe()

df.columns

"""### Categorical Feature Distribution

Check the distribution of each categorical feature to understand the values present in the dataset.
"""

df['Gender'].value_counts()

df['family_history_with_overweight'].value_counts()

df['FAVC'].value_counts()

df['CAEC'].value_counts()

df['SMOKE'].value_counts()

df['SCC'].value_counts()

df['CALC'].value_counts()

df['MTRANS'].value_counts()

"""### Target Variable Distribution

Examine the distribution of the obesity-level target variable.
"""

df['NObeyesdad'].value_counts()

df.shape

"""## 4. Data Quality Check

Check the dataset for:

- Missing values
- Duplicate records
- Potential numerical outliers

Duplicate records are identified and removed before further analysis.
"""

df.isnull().sum()

df.duplicated().sum()

"""### Outlier Detection

Use the Interquartile Range (IQR) method to identify potential outliers in numerical variables.

IQR = Q3 - Q1

Lower Bound = Q1 - 1.5 × IQR

Upper Bound = Q3 + 1.5 × IQR

The number of potential outliers is calculated for each numerical feature.
"""

numeric_cols=['Age','Height','Weight','FCVC','NCP','CH2O','FAF','TUE']
for col in numeric_cols:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)
  IQR=Q3-Q1
  lower_bound=Q1-1.5*IQR
  upper_bound=Q3+1.5*IQR
  outlier=df[(df[col]<lower_bound) | (df[col]>upper_bound)]
  print(len(outlier))

df[df.duplicated(keep=False)]

df.drop_duplicates(inplace=True)

df.shape

"""### Numerical Feature Distribution — Boxplots

Visualize the numerical variables using boxplots to inspect their distributions and potential extreme values.
"""

for col in numeric_cols:
  plt.figure(figsize=(4,6))
  sns.boxplot(data=df,y=col)
  plt.show()

"""### Numerical Feature Distributions

Use histograms with KDE curves to understand the distribution of numerical variables such as age, height, weight, physical activity, and water consumption.
"""

for col in numeric_cols:
  plt.figure(figsize=(4,6))
  sns.histplot(df[col],kde=True)
  plt.show()

"""## 5. Exploratory Data Analysis

### Categorical Features vs Obesity Level

Analyze categorical variables across obesity categories to identify differences in lifestyle and demographic characteristics.
"""

categorical_col=['Gender','CAEC','CALC','MTRANS']
for col in categorical_col:
  plt.figure(figsize=(6,7))
  sns.countplot(data=df,y=col,hue='NObeyesdad')
  plt.show()

sns.scatterplot(data=df,x='Age',y='Height',hue='NObeyesdad')
plt.show()

"""### Correlation Analysis

Analyze relationships between numerical variables using a correlation matrix.

A heatmap is used to visually identify positive and negative relationships between numerical features.
"""

df.corr(numeric_only=True)

sns.heatmap(df.corr(numeric_only=True),annot=True,cmap='vlag')
plt.show()

df.dtypes

plt.figure(figsize=(10,5))
sns.countplot(data=df, x='NObeyesdad')
plt.xticks(rotation=45)
plt.show()

"""### Target Variable Analysis

Analyze the distribution of obesity levels and examine how obesity categories are distributed across gender.
"""

pd.crosstab(
    df['Gender'],
    df['NObeyesdad'],
    normalize='index'
) * 100

"""## 6. Feature Engineering

Create additional features from the existing variables to provide the machine learning models with more meaningful representations of the data.

### BMI

Calculate Body Mass Index using:

BMI = Weight / Height²

BMI provides a derived measure based on height and weight.
"""

df['BMI']=df['Weight']/(df['Height']**2)
df['BMI']

sns.histplot(data=df, x='BMI', kde=True)
plt.show()

sns.boxplot(data=df, x='NObeyesdad', y='BMI')
plt.xticks(rotation=45)
plt.show()

"""### Lifestyle Score

Create a simple lifestyle score based on three binary lifestyle-related variables:

- Frequent high-calorie food consumption
- Smoking
- Calorie monitoring

Each "yes" contributes one point to the score.
"""

df['lifestyle_score'] = (
    df['FAVC'].map({'yes':1, 'no':0}) +
    df['SMOKE'].map({'yes':1, 'no':0}) +
    df['SCC'].map({'yes':1, 'no':0})
)

"""### Activity-Hydration Ratio

Create a derived feature combining physical activity frequency and water consumption.

The denominator includes +1 to avoid division by zero.
"""

df['activity_hydration_ratio'] = df['FAF'] / (df['CH2O'] + 1)

for col in numeric_cols + ['BMI']:
    plt.figure(figsize=(8,5))
    sns.boxplot(data=df, x='NObeyesdad', y=col)
    plt.xticks(rotation=45)
    plt.title(f'{col} vs Obesity Level')
    plt.show()

sns.scatterplot(
    data=df,
    x='Weight',
    y='BMI',
    hue='NObeyesdad'
)
plt.show()

sns.scatterplot(
    data=df,
    x='FAF',
    y='Weight',
    hue='NObeyesdad'
)
plt.show()

"""# 7. Regression — Predict Weight

## Objective

Build regression models to predict **Weight** as a continuous numerical target.

The target variable is:

`Weight`

`NObeyesdad` is excluded because it is the classification target.
"""

X=df.drop(columns=['NObeyesdad','Weight'])
y=df['Weight']
numeric_featues=X.select_dtypes(include=['int64', 'float64']).columns
categorical_features=X.select_dtypes(include=['object']).columns

print(numeric_featues)
print(categorical_features)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

"""### Data Preprocessing

The dataset contains both numerical and categorical variables.

Numerical features are standardized using `StandardScaler`.

Categorical features are converted into numerical representations using `OneHotEncoder`.

A `ColumnTransformer` is used so that both preprocessing steps can be applied within a single pipeline.
"""

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_featues),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

"""## 7.1 Linear Regression

Linear Regression is used as the baseline regression model for predicting Weight.

The preprocessing and regression model are combined using a Pipeline.
"""

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

model = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred[:10])

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

"""### Regression Evaluation Metrics

The model is evaluated using:

- **MAE (Mean Absolute Error):** Average absolute prediction error.
- **MSE (Mean Squared Error):** Average squared prediction error.
- **RMSE (Root Mean Squared Error):** Square root of MSE.
- **R² Score:** Measures how much variance in the target is explained by the model.

Lower MAE and RMSE indicate smaller prediction errors, while a higher R² indicates better explanatory performance.

### Actual vs Predicted Weight

Visualize actual weight against predicted weight.

Predictions closer to the diagonal relationship between actual and predicted values indicate smaller prediction errors.
"""

plt.figure(figsize=(7,5))

sns.scatterplot(x=y_test, y=y_pred)

plt.xlabel("Actual Weight")
plt.ylabel("Predicted Weight")
plt.title("Actual vs Predicted Weight")

plt.show()

"""## 7.2 Ridge Regression

Ridge Regression is a regularized version of Linear Regression.

It adds an L2 regularization penalty to reduce the impact of large model coefficients and can help control model complexity.

The regularization strength is controlled using `alpha`.
"""

from sklearn.linear_model import Ridge
from sklearn.pipeline import Pipeline

ridge_model = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', Ridge(alpha=1.0))
])

ridge_model.fit(X_train, y_train)

ridge_pred = ridge_model.predict(X_test)

ridge_mae = mean_absolute_error(y_test, ridge_pred)
ridge_rmse = np.sqrt(mean_squared_error(y_test, ridge_pred))
ridge_r2 = r2_score(y_test, ridge_pred)

print("Ridge")
print("MAE:", ridge_mae)
print("RMSE:", ridge_rmse)
print("R²:", ridge_r2)

"""## 7.3 Lasso Regression

Lasso Regression uses L1 regularization.

L1 regularization can shrink some model coefficients toward zero, which can also help with feature selection.

The regularization strength is controlled using `alpha`.
"""

from sklearn.linear_model import Lasso

lasso_model = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', Lasso(alpha=0.1))
])

lasso_model.fit(X_train, y_train)

lasso_pred = lasso_model.predict(X_test)

lasso_mae = mean_absolute_error(y_test, lasso_pred)
lasso_rmse = np.sqrt(mean_squared_error(y_test, lasso_pred))
lasso_r2 = r2_score(y_test, lasso_pred)

print("Lasso")
print("MAE:", lasso_mae)
print("RMSE:", lasso_rmse)
print("R²:", lasso_r2)

"""## 7.4 Regression Model Comparison

Compare Linear Regression, Ridge Regression, and Lasso Regression using:

- MAE
- RMSE
- R²

This provides a consolidated view of regression model performance.
"""

results = pd.DataFrame({
    'Model': [
        'Linear Regression',
        'Ridge',
        'Lasso'
    ],
    'MAE': [
        mae,
        ridge_mae,
        lasso_mae
    ],
    'RMSE': [
        rmse,
        ridge_rmse,
        lasso_rmse
    ],
    'R2': [
        r2,
        ridge_r2,
        lasso_r2
    ]
})

results

"""# 8. Classification — Predict Obesity Level

## Objective

Build classification models to predict the obesity category:

`NObeyesdad`

Since this is a categorical target, classification algorithms are used.
"""

X = df.drop(columns=['NObeyesdad', 'Weight'])
y = df['NObeyesdad']
y.value_counts()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""## 8.1 Logistic Regression

Logistic Regression is used as a baseline classification model.

The model predicts the probability of observations belonging to the different obesity categories.
"""

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

logistic_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

logistic_model.fit(X_train, y_train)

logistic_pred = logistic_model.predict(X_test)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

logistic_accuracy = accuracy_score(y_test, logistic_pred)
logistic_precision = precision_score(
    y_test, logistic_pred, average='weighted'
)
logistic_recall = recall_score(
    y_test, logistic_pred, average='weighted'
)
logistic_f1 = f1_score(
    y_test, logistic_pred, average='weighted'
)

print("Logistic Regression")
print("Accuracy:", logistic_accuracy)
print("Precision:", logistic_precision)
print("Recall:", logistic_recall)
print("F1:", logistic_f1)

"""## 8.2 K-Nearest Neighbors (KNN)

KNN classifies an observation based on the classes of nearby observations.

The model is configured with `n_neighbors=5`.
"""

from sklearn.neighbors import KNeighborsClassifier

knn_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', KNeighborsClassifier(n_neighbors=5))
])

knn_model.fit(X_train, y_train)

knn_pred = knn_model.predict(X_test)

knn_accuracy = accuracy_score(y_test, knn_pred)
knn_precision = precision_score(
    y_test, knn_pred, average='weighted'
)
knn_recall = recall_score(
    y_test, knn_pred, average='weighted'
)
knn_f1 = f1_score(
    y_test, knn_pred, average='weighted'
)

print("KNN")
print("Accuracy:", knn_accuracy)
print("Precision:", knn_precision)
print("Recall:", knn_recall)
print("F1:", knn_f1)

"""## 8.3 Decision Tree

Decision Tree classification uses a sequence of decision rules to divide observations into different classes.

A maximum depth of 10 is used to control tree complexity.
"""

from sklearn.tree import DecisionTreeClassifier

dt_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(
        max_depth=10,
        random_state=42
    ))
])

dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_pred)
dt_precision = precision_score(
    y_test, dt_pred, average='weighted'
)
dt_recall = recall_score(
    y_test, dt_pred, average='weighted'
)
dt_f1 = f1_score(
    y_test, dt_pred, average='weighted'
)

print("Decision Tree")
print("Accuracy:", dt_accuracy)
print("Precision:", dt_precision)
print("Recall:", dt_recall)
print("F1:", dt_f1)

"""## 8.4 Random Forest

Random Forest is an ensemble learning algorithm that combines multiple decision trees.

The model uses:

- 200 trees
- Maximum depth of 10
- Random state of 42
"""

from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        random_state=42
    ))
])

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

rf_accuracy = accuracy_score(y_test, rf_pred)
rf_precision = precision_score(
    y_test, rf_pred, average='weighted'
)
rf_recall = recall_score(
    y_test, rf_pred, average='weighted'
)
rf_f1 = f1_score(
    y_test, rf_pred, average='weighted'
)

print("Random Forest")
print("Accuracy:", rf_accuracy)
print("Precision:", rf_precision)
print("Recall:", rf_recall)
print("F1:", rf_f1)

"""### Classification Evaluation Metrics

The classification models are evaluated using:

- Accuracy
- Precision
- Recall
- F1 Score

Weighted averaging is used for the multiclass classification metrics.

## 8.5 Classification Model Comparison

Compare all classification models using Accuracy, Precision, Recall, and F1 Score.

This allows the performance of different classification algorithms to be evaluated using the same test set.
"""

classification_results = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'KNN',
        'Decision Tree',
        'Random Forest'
    ],
    'Accuracy': [
        logistic_accuracy,
        knn_accuracy,
        dt_accuracy,
        rf_accuracy
    ],
    'Precision': [
        logistic_precision,
        knn_precision,
        dt_precision,
        rf_precision
    ],
    'Recall': [
        logistic_recall,
        knn_recall,
        dt_recall,
        rf_recall
    ],
    'F1': [
        logistic_f1,
        knn_f1,
        dt_f1,
        rf_f1
    ]
})

classification_results

"""## 8.6 Confusion Matrix

A confusion matrix is used to examine the Random Forest predictions across individual obesity categories.

Rows represent actual classes and columns represent predicted classes.

The matrix helps identify which obesity categories are correctly or incorrectly classified.
"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, rf_pred)

plt.figure(figsize=(10, 7))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=rf_model.classes_,
    yticklabels=rf_model.classes_
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Random Forest Confusion Matrix")

plt.xticks(rotation=45)
plt.yticks(rotation=0)

plt.show()

"""# 9. Unsupervised Learning — K-Means Clustering

## Objective

Use K-Means clustering to discover groups of individuals based on demographic, lifestyle, activity, and related features.

No target variable is used when creating the clusters.

`NObeyesdad` and `Weight` are excluded from the clustering input.
"""

X_cluster = df.drop(columns=['NObeyesdad', 'Weight'])

numeric_features = [
    'Age',
    'Height',
    'FCVC',
    'NCP',
    'CH2O',
    'FAF',
    'TUE',
    'BMI',
    'lifestyle_score',
    'activity_hydration_ratio'
]

categorical_features = [
    'Gender',
    'family_history_with_overweight',
    'FAVC',
    'CAEC',
    'SMOKE',
    'SCC',
    'CALC',
    'MTRANS'
]

"""### Clustering Preprocessing

Numerical features are standardized using `StandardScaler`.

Categorical features are converted using `OneHotEncoder`.

This creates a numerical feature matrix suitable for K-Means clustering.
"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

preprocessor_cluster = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

X_processed = preprocessor_cluster.fit_transform(X_cluster)

X_processed.shape

"""## 9.1 K-Means Clustering

K-Means divides observations into a predefined number of clusters.

Each observation is assigned to the cluster with the nearest centroid.

An initial configuration of 4 clusters is used.
"""

from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

cluster_labels = kmeans.fit_predict(X_processed)

df['Cluster'] = cluster_labels

df['Cluster'].value_counts().sort_index()

"""## 9.2 Elbow Method

The Elbow Method evaluates different values of K using K-Means inertia.

Inertia measures the sum of squared distances between observations and their assigned cluster centroids.

The resulting curve can help identify a suitable number of clusters.
"""

import matplotlib.pyplot as plt

inertia = []

for k in range(2, 11):

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    kmeans.fit(X_processed)

    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))

plt.plot(range(2,11), inertia, marker='o')

plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method')

plt.show()

"""## 9.3 Silhouette Score

Calculate the Silhouette Score for different numbers of clusters.

The Silhouette Score measures how similar an observation is to its own cluster compared with other clusters.

It provides an additional measure for assessing cluster separation.
"""

from sklearn.metrics import silhouette_score

silhouette_scores = []

for k in range(2, 11):

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(X_processed)

    score = silhouette_score(X_processed, labels)

    silhouette_scores.append(score)

plt.figure(figsize=(8,5))

plt.plot(
    range(2,11),
    silhouette_scores,
    marker='o'
)

plt.xlabel('Number of Clusters (K)')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Score for Different K')

plt.show()

"""## 9.4 Final K-Means Clustering

Apply the selected number of clusters and assign each observation to its final cluster.

The cluster labels are stored in the `Cluster` column.
"""

kmeans_final = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

df['Cluster'] = kmeans_final.fit_predict(X_processed)

df['Cluster'].value_counts().sort_index()

"""## 9.5 Cluster Profiling

Analyze the characteristics of each cluster using:

- Mean numerical values
- Median numerical values
- Gender distribution
- Transportation distribution
- Eating behavior
- Obesity-level distribution
"""

cluster_profile = df.groupby('Cluster')[numeric_features].mean()

cluster_profile

df.groupby('Cluster')[numeric_features].median()

pd.crosstab(
    df['Cluster'],
    df['Gender'],
    normalize='index'
) * 100

pd.crosstab(
    df['Cluster'],
    df['MTRANS'],
    normalize='index'
) * 100

pd.crosstab(
    df['Cluster'],
    df['CAEC'],
    normalize='index'
) * 100

pd.crosstab(
    df['Cluster'],
    df['NObeyesdad'],
    normalize='index'
) * 100

"""## 9.6 PCA Visualization

Principal Component Analysis (PCA) is used to reduce the processed feature space to two dimensions.

The first two principal components are used to visualize the K-Means clusters.
"""

from sklearn.decomposition import PCA

X_dense = X_processed

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_dense)

pca_df = pd.DataFrame({
    'PC1': X_pca[:, 0],
    'PC2': X_pca[:, 1],
    'Cluster': df['Cluster']
})

plt.figure(figsize=(9,6))

sns.scatterplot(
    data=pca_df,
    x='PC1',
    y='PC2',
    hue='Cluster'
)

plt.title('K-Means Clusters - PCA Visualization')
plt.show()

df['Cluster'] = kmeans.labels_

cluster_profile = df.groupby('Cluster')[numeric_features].mean()

cluster_profile

df['Cluster'].value_counts().sort_index()

pd.crosstab(
    df['Cluster'],
    df['NObeyesdad'],
    normalize='index'
).round(3) * 100

"""## 9.7 Final Cluster Interpretation

Compare the clusters using BMI, lifestyle score, activity, hydration, age, and other relevant features.

`NObeyesdad` is examined after clustering to understand the obesity-level composition of the discovered clusters.

The target variable is not used to create the clusters.
"""

df.groupby('Cluster')[
    ['BMI', 'lifestyle_score', 'activity_hydration_ratio',
     'Age', 'FAF', 'CH2O']
].mean().round(2)

"""# 10. Conclusion

This project demonstrated three major machine learning approaches using the obesity dataset.

### Regression
Predicted Weight using:

- Linear Regression
- Ridge Regression
- Lasso Regression

### Classification
Predicted Obesity Level using:

- Logistic Regression
- KNN
- Decision Tree
- Random Forest

### Unsupervised Learning
Discovered groups of individuals using:

- K-Means Clustering
- Elbow Method
- Silhouette Score
- PCA

### Overall Workflow

Data Loading
→ Data Cleaning
→ EDA
→ Feature Engineering
→ Preprocessing
→ Regression
→ Classification
→ Clustering
→ Model Evaluation
→ Cluster Interpretation

This project provided hands-on practice with the complete machine learning workflow from raw data exploration through supervised and unsupervised learning.
"""